/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClassModifier */

#ifndef _Included_ClassModifier
#define _Included_ClassModifier
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
